export const BILLING_PLANS = [
  {
    slug: "starter" as const,
    name: "Starter",
    price: 5,
    standardPrice: 9,
    introductoryMonths: 3,
    popular: false,
    features: [
      "1 Instagram account",
      "3 keyword rules",
      "500 DMs / month",
      "Automatic comment-to-DM replies",
      "Basic analytics",
      "Email support via the contact form",
      "Cancel anytime",
    ],
  },
  {
    slug: "creator" as const,
    name: "Creator",
    price: 19,
    popular: true,
    features: [
      "2 Instagram accounts",
      "15 keyword rules",
      "5,000 DMs / month",
      "Advanced analytics",
      "Activity tracking",
      "Email support via the contact form",
      "Cancel anytime",
    ],
  },
  {
    slug: "pro" as const,
    name: "Pro",
    price: 49,
    features: [
      "5 Instagram accounts",
      "Unlimited keyword rules",
      "25,000 DMs / month",
      "Full analytics suite",
      "Team members (3 seats)",
      "API access",
      "Email support via the contact form",
      "Cancel anytime",
    ],
  },
];
