export const BILLING_PLANS = [
  {
    slug: "starter" as const,
    name: "Starter",
    price: 9,
    annualPrice: 86.4,
    offerPrice: 4.5,
    introductoryMonths: 3,
    popular: false,
    features: [
      "1 Instagram account",
      "5 keyword rules",
      "1,000 DMs / month",
      "Automatic comment-to-DM replies",
      "Analytics dashboard",
      "Activity log",
      "Email support via the contact form",
      "Cancel anytime",
    ],
  },
  {
    slug: "creator" as const,
    name: "Creator",
    price: 19,
    annualPrice: 182.4,
    offerPrice: 9.5,
    introductoryMonths: 3,
    popular: true,
    features: [
      "3 Instagram accounts",
      "Unlimited keyword rules",
      "10,000 DMs / month",
      "Analytics dashboard",
      "Activity log",
      "Email support via the contact form",
      "Cancel anytime",
    ],
  },
  {
    slug: "pro" as const,
    name: "Pro",
    price: 49,
    annualPrice: 470.4,
    offerPrice: 24.5,
    introductoryMonths: 3,
    features: [
      "15 Instagram accounts",
      "Unlimited keyword rules",
      "25,000 DMs / month",
      "Analytics dashboard",
      "Activity log",
      "Email support via the contact form",
      "Cancel anytime",
    ],
  },
];
